### ISSUE TITLE
Convertible concept fails to compile in gcc trunk due to removal of the __is_convertible_to intrinsic

### ISSUE THREAD

**Issue by tahonermann** [asutton/origin#1]
origin/core/concepts.hpp declares a Convertible concept that relies on a compiler supplied __is_convertible_to intrinsic.  Recent gcc builds fail to compile this concept due to removal of the intrinsic.

__is_convertible_to was removed in gcc svn revision 215735:
https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=215735

Example reduced test case using a recent gcc trunk build (5.0, c++-concepts, svn revision 219158):

$ cat convertible.cpp 
template<typename T, typename U>
concept bool
Convertible() {
    return __is_convertible_to(T, U);
}

$ g++ --version
g++ (GCC) 5.0.0 20141112 (experimental)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ -std=c++1z -c convertible.cpp 
convertible.cpp: In function ‘constexpr bool Convertible()’:
convertible.cpp:4:33: error: expected primary-expression before ‘,’ token
     return __is_convertible_to(T, U);
                                 ^
convertible.cpp:4:36: error: expected primary-expression before ‘)’ token
     return __is_convertible_to(T, U);
                                    ^
convertible.cpp:4:36: error: there are no arguments to ‘__is_convertible_to’ that depend on a template parameter, so a declaration of ‘__is_convertible_to’ must be available [-fpermissive]
convertible.cpp:4:36: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)

**Comment by hgkamath** [comment]
Unsure if right, but I used this to push through with compile
GNU C++ (GCC) version 5.0.0 20141112 (experimental) c++-concept branch

```
diff ../../../../origin/core/concepts.hpp.orig.gk ../../../../origin/core/concepts.hpp
33c33
<   Convertible() { return __is_convertible_to(T, U); }
---
>   Convertible() { return std::is_convertible<T, U>::value ; }


 diff ../../../../origin/core/concepts.test/difference_type.cpp.orig.gk ../../../../origin/core/concepts.test/difference_type.cpp
16c16,17
<   using difference_type = int;
---
>   //using difference_type = int;
>   typedef int difference_type ;

diff ../../../../origin/core/concepts.test/value_type.cpp.orig.gk ../../../../origin/core/concepts.test/value_type.cpp
16c16,17
<   using value_type = int;
---
>   //using value_type = int;
>   typedef int value_type ;

```

there was a internal compiler segmentation error with the "using" statements in the many other files
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65269

I do not think however, the origin library will compile against conceptgcc, as the alias template ("using" feature) is not working. 

we need to be pointed to the right gcc repository/branch/version for which the origin library works.

**Comment by hgkamath** [comment]
noting here that : 
gcc  from https://bitbucket.org/Blzut3/c-concepts/src 
and origin from https://github.com/asutton/origin
compiled and usable as on 20150312

**Comment by tahonermann** [comment]
Thank you!  This appears to be resolved.  Closing the issue.
