### ISSUE TITLE
Uninitialized copy and move return garbage iterators. 

### ISSUE THREAD

**Issue by ilyapopov** [asutton/origin#4]
`uninitialized_copy` and `uninitialized_move` algorithms do not contain any return statement, and thus returning garbage. Supposedly they should return the final iterator into the second range.

**Comment by asutton** [comment]
Are you actually trying to _use_ origin? That would be first.

Fixed, but not tested.

**Comment by ilyapopov** [comment]
No, I don't, sorry. I was just reading the code for educational purposes.

**Comment by asutton** [comment]
No worries... Origin is primarily intended for my own educational purposes
:)

Andrew Sutton
